RDFMVC/RDFMVC/Controllers/RDFQueryController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RDFMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Script.Services;
using System.Web.Services;
using System.Xml.Linq;
using VDS.Common.Collections;
using VDS.RDF;
using VDS.RDF.Parsing;
using VDS.RDF.Query;
using VDS.RDF.Query.Datasets;
using VDS.RDF.Writing;

namespace RDFMVC.Controllers
{
    public class RDFQueryController : Controller
    {

        private readonly ISession _ISession;
        private readonly IRdfFile _IRdfFile;

        public RDFQueryController(ISession _ISessionRepo, IRdfFile _IRdfFileRepo)
        {
            _ISession = _ISessionRepo;
            _IRdfFile = _IRdfFileRepo;
        }
        // GET: RDFQuery
        [HttpGet]
        public ActionResult Index()
        {
            Query model = new Query();
            string AtacehedFileName = GetAttachedOwlFile();
            //In case the file deleted from the DB, But still Attatced.
            if (AtacehedFileName.Equals("Error"))
            {
                model.query = "Please, upload your OWL file, or choose one from Rdf Files Tab.";
            }
            else { 

            TempData["FileName"] = string.Format("You Are Using "+AtacehedFileName);
          
            model.query = "select * where { ?subject ?predicate ?object} Limit 10";
             
            }
            return View(model);
        }
         
        [HttpGet]
        [ValidateInput(false)]
        public PartialViewResult ExecuteQuery(Query data )
        {
            ResultSet _ResultSet = new ResultSet(); 
            
            SparqlResultSet _SparqlResultSet = null; 
            //string query = Request.Unvalidated["SparqlQuery"]; 
            // Create a Triple Collection with only a subject index
            BaseTripleCollection tripleCollection = new TreeIndexedTripleCollection(
                true, false, false, false, false, false, MultiDictionaryMode.AVL); 
                // Create a Graph using the customized triple collection
                //  Graph g = new Graph(tripleCollection); 
                TripleStore _TripleStore = new TripleStore(); 
            string _OwlFileName = GetAttachedOwlFile(); 
            if (!_OwlFileName.Equals("Error"))
            { 
                string _OWLFilePath = Server.MapPath("~/DataSets/"+ _OwlFileName); 
                _TripleStore.LoadFromFile(_OWLFilePath); 
                ISparqlDataset _ISparqlDataset = new InMemoryDataset(_TripleStore); 
                LeviathanQueryProcessor _LeviathanQueryProcessor = new LeviathanQueryProcessor(_ISparqlDataset); 
                SparqlQueryParser _SparqlQueryParser = new SparqlQueryParser(); 
            //  Then we can parse a SPARQL string into a query
            if (ModelState.IsValid)
            {
                try { 
                SparqlQuery _SparqlQuery = _SparqlQueryParser.ParseFromString(data.query);
                var results = _LeviathanQueryProcessor.ProcessQuery(_SparqlQuery);
                    _SparqlResultSet = (SparqlResultSet)results;

                        ///
                        _ResultSet.Columns= _SparqlResultSet.Variables;
                        string value = null;
                        foreach (SparqlResult _SparqlResult in _SparqlResultSet)
                        {
                            foreach (var _Col in _ResultSet.Columns)
                            {
                                INode _Node;
                                if (_SparqlResult.TryGetValue(_Col, out _Node))
                                {
                                    switch (_Node.NodeType)
                                    {
                                        case NodeType.Uri:
                                            value = ((IUriNode)_Node).Uri.AbsoluteUri;
                                            break;
                                        case NodeType.Literal:

                                            value = ((ILiteralNode)_Node).Value;
                                            break;
                                        default:
                                            Console.WriteLine("Error Node");
                                            ModelState.AddModelError("", "Error in The Node Type ");
                                            break;
                                    } 
                                }
                                else
                                {
                                    value = String.Empty;
                                }
                                //Data To Rows  
                                _ResultSet.Rows.Enqueue(value);
                            }
                        }

                        ///



                    }
                 catch (RdfParseException e)
                 {
                        //  Console.SetError(e.ToString());
                        ModelState.AddModelError("", "Error in The Syntax " + e.Message);
                        TempData["message"] = string.Format("Syntaxerror"); 
                } 
            }
            else
            {
                TempData["message"] = string.Format("EmptyQuery"); 
                }
            }
            else
            {
                TempData["message"] = string.Format("ChooseDb"); 
            } 
            return PartialView("_ExecuteQuery", _ResultSet);
        }

        public string GetAttachedOwlFile()
        {
            Session model_Session = new Session();
            RdfFile model_RdfFile = new RdfFile();
            string FileName=null;
            string CurrentUser = User.Identity.Name;

            if (CurrentUser.Equals(""))
            {
                //If there is no Session(User does not login) will user the defualt user admin@admin.com
                CurrentUser = "admin@admin.com";
                model_Session = _ISession.SessionByUserId(CurrentUser);//To get the FileId from Session Table by UserId
                model_RdfFile = _IRdfFile.Details(model_Session.FileId);//To get the File Name from RdfFile Table by FileId
              
            }
            else {
             model_Session = _ISession.SessionByUserId(CurrentUser);//To get the FileId from Session Table by UserId
             model_RdfFile = _IRdfFile.Details(model_Session.FileId);//To get the File Name from RdfFile Table by FileId
             
            }
            if (model_RdfFile == null)
            {
             FileName = "Error";
            }
            else
            {
                FileName = model_RdfFile.FileName;
            }
            return FileName;
        }

        //Old Verion 1.5
        //public string GetXmlDbName()
        //{

        //    string _FileName=null;
        //    string realPath;
        //    realPath = Server.MapPath("~/DataSets/AttachedDB.xml");
        //    XElement xelement = XElement.Load(realPath);
        //    IEnumerable<XElement> nodes = xelement.Elements();

        //    foreach (var node in nodes)
        //    {
        //        _FileName = node.Attribute("name").Value;

        //    }
        //    return _FileName;
        //}

    }
}

RDFMVC/RDFMVC/Controllers/UploadFileController.cs
using RDFMVC.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Xml;

namespace RDFMVC.Controllers
{
    public class UploadFileController : Controller
    {
        private readonly IRdfFile _IRdfFile;
        private readonly ISession _ISession;

        public UploadFileController(IRdfFile _IRdfFileRepo, ISession _SessionRepo)
        {
            _IRdfFile = _IRdfFileRepo;//To add owl File to the DB.
            _ISession = _SessionRepo;//To Create Seesion for the User and save the attached owl file.
        }
        // GET: UploadFile
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ActionResult Delete(int? Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadGateway);
            }
            RdfFile model = _IRdfFile.Details(Id);
            
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }
        [HttpPost, ActionName("Delete")]
        [Authorize]
        public ActionResult DeleteConfirm(int? Id)
        {

            RdfFile model = _IRdfFile.Details(Id);

            if (model.UserId == User.Identity.Name)
            {
                RdfFile model_deleted = _IRdfFile.Delete(Id);

                if (model_deleted != null)
                {
                    TempData["message"] = string.Format("{0} has been deleted successfully", model.FileName);
                }
                return RedirectToAction("LoadOwlPublicFiles");
            }
            TempData["message"] = string.Format("You Can't Delete this File {0} , it is not your file.", model.FileName);
            
            return RedirectToAction("LoadOwlPublicFiles");
        }
        public ActionResult LoadOwlPublicFiles()
        {
            IEnumerable<RdfFile> _list;
            _list = _IRdfFile.RdfFileIQueryable.Where(m =>m.IsPublic==true);//Show Public OWl Only
            return PartialView(_list);
        }
        public ActionResult LoadMyOwlFiles()
        {
            IEnumerable<RdfFile> _list;
            _list = _IRdfFile.RdfFileIQueryable.Where(m => m.UserId==User.Identity.Name);//Show My OWl Only
            return PartialView(_list);
        }
        //Old Version
        //public ActionResult LoadXMLFile()
        //{

        //    List<XMLFile> _list=new List<XMLFile>();
        //    string realPath;
        //    realPath = Server.MapPath("~/DataSets/Database.xml");
        //    XElement xelement = XElement.Load(realPath);
        //    IEnumerable<XElement> nodes = xelement.Elements();

        //    foreach (var node in nodes)
        //    {
        //        XMLFile model = new XMLFile();
        //        model.filename = node.Attribute("name").Value;
        //        model.Date = node.Attribute("date").Value;
        //        _list.Add(model);
        //    } 
        //    return PartialView(_list);
        //}

        [AcceptVerbs(HttpVerbs.Post)]
       public JsonResult Upload()
        {
            RdfFile model = new RdfFile();
            string _FileName = string.Empty;

            if (System.Web.HttpContext.Current.Request.Files.AllKeys.Any())
            {
                var file = System.Web.HttpContext.Current.Request.Files["MyFile"];
                var IsPublic = System.Web.HttpContext.Current.Request.Form["IsPublic"];//True Make it Pulic
                 
                //Read OWL only...
                var _ext = Path.GetExtension(file.FileName);
                if (_ext.Equals(".owl"))
                {

                if (file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);

                    Random rng = new Random();
                   int rand= rng.Next(1000);

                    var _comPath = Server.MapPath("/DataSets/Id_") + rand +"_" + fileName;
                    _FileName = "Id_" + rand + "_" + fileName;

                    ViewBag.Msg = _comPath;
                    var path = _comPath;

                    // Saving file in Original Mode
                    file.SaveAs(path);


                        //here to add Image Path to You Database ,
                        model.FileName = _FileName;
                        model.UserId = User.Identity.Name;//Need to read it form Identity
                        model.IsPublic = Convert.ToBoolean(IsPublic);
                        model.UploadDate = DateTime.Now;
                        model.Size = (file.ContentLength/1024);
                        _IRdfFile.Save(model);
                        // SaveToXMLDB(_FileName);  //From Old Version
                        // AttachOWLFile(_FileName);//From Old Version
                    }
                }
                else
                {
                    TempData["FileType"] = string.Format("");
                   return Json("false");
                }

            }

            return Json(Convert.ToString(_FileName), JsonRequestBehavior.AllowGet);
        }
        //Old Version
        //public void SaveToXMLDB(string filename)
        //{
        //    string realPath;
        //    realPath = Server.MapPath("~/DataSets/Database.xml");
        //    XmlDocument db = new XmlDocument();
        //    db.Load(realPath);
        //    Create the node name
        //    XmlNode Files = db.SelectSingleNode("Files");
        //    XmlNode File = db.CreateNode(XmlNodeType.Element, "File", null);
        //    XmlAttribute name = db.CreateAttribute("name");
        //    XmlAttribute Date = db.CreateAttribute("date");
        //    name.Value = filename;
        //    Date.Value = DateTime.Now.ToString();
        //    File.Attributes.Append(name);
        //    File.Attributes.Append(Date);
        //    Files.AppendChild(File);
        //    db.Save(realPath);
        //}


        public ActionResult SelectFile(int Id)
        {
            AttachOWLFile(Id); 
            return RedirectToAction("LoadOwlPublicFiles"); 
        }

        public void AttachOWLFile(int? FileId)
        {
            Session model = new Session();

           if(FileId != null)
            {
                model.UserId = User.Identity.Name;
                model.FileId = FileId.Value;
                model.CreatedDate = DateTime.Now;
                model.UpdateDate = DateTime.Now;//Same as CreateTime means no update.

                _ISession.Save(model);
                TempData["message"] = string.Format("You Have Select the File Number #" + FileId.Value);
            }

          
        }

        //Old Version 1.5
        //public void AttachOWLFile(string filename)
        //{
        //    string realPath;
        //    realPath = Server.MapPath("~/DataSets/AttachedDB.xml"); 
        //    XmlWriter writer = XmlWriter.Create(realPath);
        //    writer.WriteStartDocument(); 
        //    writer.WriteStartElement("Files");
        //    writer.WriteStartElement("File");
        //    writer.WriteAttributeString("name", filename); 
        //    writer.WriteEndElement();
        //    writer.WriteEndDocument(); 
        //    writer.Flush();
        //    writer.Close(); 
        //    TempData["message"] = string.Format("You Have Select the File" + " " + filename);
        //}

    }
}

RDFMVC/RDFMVC/Views/Shared/_ExecuteQuery.cshtml
 @model RDFMVC.Models.ResultSet 
<link href="~/Content/Site.css" rel="stylesheet" /> 
<h4>Query Result</h4>
<div class="container">
    @{ 
        if (TempData["message"] != null)
        {
            if (TempData["message"].Equals("ChooseDb"))
            {
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>Error !</strong> You have to Upload your OWL Files or Choose one from RDF File Tab.
                </div>
            } 
            if (TempData["message"].Equals("EmptyQuery"))
            {
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>alert !</strong> Your Query is Empty.
        </div>
            }
            if (TempData["message"].Equals("Syntaxerror")) {
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Error !</strong> You Have Syntax Error.
        </div> 
                } 
            } 
        }
</div>  
<br />
  
<div class="table-responsive" id="dvData">
    <table class="table table-bordered table-responsive table-hover table-striped" id="tblData">
         
        @{ 
            if(Model.Columns != null) { 
            <thead class="thead-light">
                <tr>
                    @foreach (var _Column in Model.Columns)
                    {
                        <th>
                             @Html.DisplayFor(col => _Column)
                        </th>
                    }
                </tr>
            </thead>
            <tbody>
                @while(Model.Rows.Count()>0)
                {
                    <tr>
                      @for (int i = 1; i <= Model.Columns.Count(); i++)
                      {
                            <td>
                                @Model.Rows.Dequeue()
                            </td> 
                        } 
                    </tr> 
                }
            </tbody>
            }
            } 
    </table> 
   
</div>
 <div id="paging" class="pagination pagination-sm"></div> 

        <script>  
        $(document).ready(function () { 
            var totalRows = $('#tblData').find('tbody tr:has(td)').length;
            var recordPerPage = 20;//Elements in one Page
            var totalPages = Math.ceil(totalRows / recordPerPage);
            var $pages = $('<div id="pages"></div>');
            for (i = 0; i < totalPages; i++) {
                $('<span class="pageNumber">&nbsp;' + (i + 1) + '</span>').appendTo($pages);
            }
            $pages.appendTo('#paging'); 
            $('.pageNumber').hover(
                function () {
                    $(this).addClass('focus');
                },
                function () {
                    $(this).removeClass('focus');
                }
            ); 
            $('table').find('tbody tr:has(td)').hide();
            var tr = $('table tbody tr:has(td)');
            for (var i = 0; i <= recordPerPage - 1; i++) {
                $(tr[i]).show();
            }
            $('span').click(function (event) {
                $('#tblData').find('tbody tr:has(td)').hide();
                var nBegin = ($(this).text() - 1) * recordPerPage;
                var nEnd = $(this).text() * recordPerPage - 1;
                for (var i = nBegin; i <= nEnd; i++) {
                    $(tr[i]).show();
                }
            });  
        }); 
    </script>

 

RDFMVC/RDFMVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Alaeddin Alhamoud</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        
        <div class="container">
           
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    <img src="~/Images/avatar-icon.png" width="30" height="30" alt="">
                </a>
                @Html.ActionLink("Sparql Query", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Rdf Files", "LoadOwlPublicFiles", "UploadFile")</li>
                   @if (Request.IsAuthenticated)
                    {
                    <li>@Html.ActionLink("My Rdf Files", "LoadMyOwlFiles", "UploadFile")</li>
                    }
                    <li>@Html.ActionLink("Query", "Index", "RDFQuery")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                   
                </ul>
               @Html.Partial("_LoginPartial")  
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sparql Query By <a href="https://www.facebook.com/alaeddinalhamoud.page">Alaeddin Alhamoud</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>